[package]
name = "cargo-unstable-api"
version = "0.0.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
proc-macro2 = "1"
quote = "1"
syn = { version = "3", features = ["extra-traits", "full", "visit"] }
