[relabel]
allow-unauthenticated = [
    "A-*",
    "C-*",
    "D-*",
    "E-*",
    "F-*",
    "I-*",
    "NLL-*",
    "O-*",
    "S-*",
    "T-*",
    "WG-*",
    "needs-fcp",
    "relnotes",
    "requires-nightly",
    "regression-*",
    "perf-*",
    "AsyncAwait-OnDeck",
    "initial-comment-period",
]

# Enable rustbot ready/author/blocked shortcuts
[shortcut]

[notify-zulip."api-change-proposal"]
zulip_stream = 327149 # #t-libs/api-changes
topic = "libs#{number}: {title}"
message_on_add = """\
@*T-libs-ping* [libs#{number} "{title}"](https://github.com/rust-lang/libs-team/issues/{number}) has been opened. You can free to discuss on Zulip or GitHub.
"""
github_comment = """\
> [!INFO]
> [A #t-libs/api-changes Zulip thread was opened for this ACP.]({zulip_topic_url}) You are free to discuss on GitHub or Zulip.
"""

[notify-zulip."ACP-accepted"]
zulip_stream = 327149 # #t-libs/api-changes
topic = "libs#{number}: {title}"
message_on_add = """\
libs#{number} has been accepted. Thank you to all who participated in the discussion.
"""
required_labels = ["api-change-proposal"]

[notify-zulip."I-libs-nominated"]
zulip_stream = 639962 # #t-libs/nominated
topic = "libs#{number}: {title}"
message_on_add = """\
@*T-libs-ping* [libs#{number} "{title}"](https://github.com/rust-lang/libs-team/issues/{number}) has been nominated for discussion.
"""
message_on_remove = """\
libs#{number} is no longer nominated.
"""
